title:               "lxmrc"
url:                 https://lxmrc.com
date_format: "%e %B %Y"
permalinks: pretty

excerpt_separator:   <!--more-->
twitter_username:   "lxmrc"

include: ['_pages']

pages_list:
  about: '/about.html'
  TIL: '/til.html'
  bookmarks: '/bookmarks.html'

collections:
  til:
    output: true
  tesserae:
    output: true

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              Alex Mercea
  email:             alex@lxmrc.com

markdown: kramdown
kramdown:
  input: GFM

highlighter: none

plugins:
  - jekyll-feed
  - jekyll-email-protect
